### ISSUE TITLE
0-based indexing for names can be confusing

### ISSUE THREAD

**Issue by hadrielk** [128technology/interfacemaps#2]
Isn't naming "ge-0" what is labeled on the device as "port 1", and "ge-1" for "port 2", etc., going to be confusing?

Or do we have no choice because we need the "first" port to always be "xxx-0"?

**Comment by reidstidolph** [comment]
@hadrielk the problem we were running into was that for meet-in-the-market 3rd party devices, number and order was all over the place, with no consistency. Some might be labeled 1-6 positioned left to right, another is labeled 0-5 positioned right to left, another might be a-f positioned in a circle. We struggled to come up with a convention that could make sense for all devices all the time. So ultimately we decided to strictly follow Junos convention for the device interface names, and we would provide clear description and documentation about the physical port labeling and orientation outside of the name.

For example, the way this currently manifests for routers built using our templates is that we provide a link to following diagram in helptext, and descriptions are populated and displayed in the UI as shown:
![image](https://user-images.githubusercontent.com/2548047/137360907-961f3dcc-3493-4cd8-ab3e-3faae41672e6.png)
![image](https://user-images.githubusercontent.com/2548047/137360496-96ac0543-8ee0-4a5d-bc45-88672ac8c448.png)

**Comment by reidstidolph** [comment]
I should add that the 0 based indexing does make more sense when it comes to our Juniper branded hardware. In that case we could control what was shown on the bezel label, and we made sure it was consistent with the device interface naming convention, and with other Juniper devices.
![image](https://user-images.githubusercontent.com/2548047/137361524-d6688032-2d33-41a4-96c1-363150ac227a.png)
